version: '3.8'

services:
    upscale-banking:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: upscale-banking-app
        ports:
            - '3000:5004'
        environment:
            - NODE_ENV=production
            - PORT=5004
        env_file:
            - .env.local
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5004/api/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        networks:
            - banking-network

networks:
    banking-network:
        driver: bridge
# For production deployment with external database
# volumes:
#   - ./logs:/app/logs
#   - /etc/ssl/certs:/etc/ssl/certs:ro
